"""projeto finalizado

Revision ID: 31b157b0dd47
Revises: 
Create Date: 2025-09-22 18:33:47.466941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b157b0dd47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(length=150), nullable=False),
    sa.Column('periodo', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('vagas_min', sa.Integer(), nullable=False),
    sa.Column('vagas_max', sa.Integer(), nullable=False),
    sa.Column('vagas_disponiveis', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nome', sa.String(length=150), nullable=False),
    sa.Column('cliente_email', sa.String(length=150), nullable=True),
    sa.Column('cliente_telefone', sa.String(length=50), nullable=True),
    sa.Column('pacote_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_reserva', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['pacote_id'], ['pacote.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('user')
    op.drop_table('pacote')
    # ### end Alembic commands ###
